image: node:10

stages:
  - build

build:
  stage: 'build'
  script:
    - npm install -g @angular/cli@6.2.1
    - npm install
    - ng build
    - mv dist/fossilizer/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
