image: node:10

stages:
  - build

build:
  stage: 'build'
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run build --prod
    - cp dist/futurice/* public/
  artifacts:
    paths:
      - public
  only:
    - master
